# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extimage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='extimage',
            name='file_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extended_app_extimage_file', serialize=False, to='filer.File'),
        ),
    ]
