# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_image', '0002_auto_20160621_1510'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='file_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_image_image_file', serialize=False, to='filer.File'),
        ),
    ]
